from __future__ import annotations


class 迁移错误(Exception):
    def __init__(self, code: str, message: str = "") -> None:
        self.code = code
        self.message = message or code
        super().__init__(f"{code}: {self.message}")


CROSS_LAYER_SCHEMA_MISSING = "CROSS_LAYER_SCHEMA_MISSING"
CROSS_LAYER_SCHEMA_ID_DUPLICATED = "CROSS_LAYER_SCHEMA_ID_DUPLICATED"
CROSS_LAYER_SCHEMA_REF_UNRESOLVED = "CROSS_LAYER_SCHEMA_REF_UNRESOLVED"
MIGRATION_CONTEXT_REQUIRED = "MIGRATION_CONTEXT_REQUIRED"
L1_DOMAIN_MAPPING_MISSING = "L1_DOMAIN_MAPPING_MISSING"
PRIMARY_FINDING_REFERENCE_MISSING = "PRIMARY_FINDING_REFERENCE_MISSING"
L2_REPAIR_SEMANTICS_AMBIGUOUS = "L2_REPAIR_SEMANTICS_AMBIGUOUS"
L3_RESULT_INCONSISTENT = "L3_RESULT_INCONSISTENT"
EVIDENCE_SOURCE_AMBIGUOUS = "EVIDENCE_SOURCE_AMBIGUOUS"
UNKNOWN_V1_FIELD = "UNKNOWN_V1_FIELD"
UNKNOWN_STATUS = "UNKNOWN_STATUS"
ROUTE_RULE_NOT_FOUND = "ROUTE_RULE_NOT_FOUND"
